In [ ]:
# Write a program to cluster a set of points using K-means for IRIS dataset. Consider, K=3, clusters. Consider Euclidean distance as the distance measure. Randomly initialize a cluster mean as one of the data points. Iterate at least for 10 iterations. After iterations are over, print the final cluster means for each of the clusters.

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\KARAN\Downloads\DSML_PRACTICAL\DSML_PRACTICAL\Datasets\IRIS.csv")

In [3]:
# Number of clusters and Iterations

K = 3
iterations = 10

# Ensure K is less than or equal to the number of rows in the dataframe
# Ensure K is valid
if K > len(data):
    raise ValueError("Number of clusters K cannot be greater than the number of data points")

In [4]:
# Randomly Initialize cluster means using .sample to avoid index mismatch
np.random.seed(42)  # For reproducibility
initial_means = data.sample(n=K, replace=False, random_state=42).values
cluster_means = initial_means

In [5]:
## Function to compute Euclidean Distance

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

In [6]:
# Ensure numerical data consistency
numerical_data = data.select_dtypes(include=[np.number])

# Initialize cluster means
cluster_means = numerical_data.sample(n=K, random_state=42).values

for i in range(iterations):
    # Assign each point to the nearest cluster
    clusters = []
    for index, point in numerical_data.iterrows():
        distances = [euclidean_distance(point.values, mean) for mean in cluster_means]
        cluster = np.argmin(distances)
        clusters.append(cluster)

    # Update cluster means
    new_means = []
    for k in range(K):
        cluster_points = numerical_data.iloc[np.where(np.array(clusters) == k)]
        if not cluster_points.empty:
            new_mean = cluster_points.mean().values
        else:
            new_mean = cluster_means[k]
        new_means.append(new_mean)

    cluster_means = np.array(new_means)


In [7]:
## Print Final Cluster Means

print("Final Cluster Means after 10 Iterations: ")
for idx, mean in enumerate(cluster_means):
    print(f"Cluster {idx + 1}: {mean}")

Final Cluster Means after 10 Iterations: 
Cluster 1: [5.9016129  2.7483871  4.39354839 1.43387097]
Cluster 2: [5.006 3.418 1.464 0.244]
Cluster 3: [6.85       3.07368421 5.74210526 2.07105263]


In [4]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\Users\KARAN\Downloads\DSML_PRACTICAL\DSML_PRACTICAL\Datasets\IRIS.csv")
points = df[['sepal_length','sepal_width', 'petal_length', 'petal_width']].values

# points = np.array([
#     [2, 10],  # P1
#     [2, 5],   # P2
#     [8, 4],   # P3
#     [5, 8],   # P4
#     [7, 5],   # P5
#     [6, 4],   # P6
#     [1, 2],   # P7
#     [4, 9]    # P8
# ])

# ininal_c=np.array([[2,10],[5,8],[1,2]])

km=KMeans(n_clusters=3,init='random',max_iter=10,random_state=0)
km.fit(points)

centr=km.cluster_centers_
l=km.labels_
s=np.bincount(l)
print(centr)
print(s)

[[5.006      3.418      1.464      0.244     ]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.9016129  2.7483871  4.39354839 1.43387097]]
[50 38 62]


In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
# df=pd.read_csv('Datasets\Lipstick.csv')
points = np.array([
    [2, 10],  # P1
    [2, 5],   # P2
    [8, 4],   # P3
    [5, 8],   # P4
    [7, 5],   # P5
    [6, 4],   # P6
    [1, 2],   # P7
    [4, 9]    # P8
])

ininal_c=np.array([[2,10],[5,8],[1,2]])

km=KMeans(n_clusters=3,n_init=1,init=ininal_c,max_iter=10,random_state=0)
km.fit(points)

centr=km.cluster_centers_
l=km.labels_
s=np.bincount(l)
print(centr)
print(s)

[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[3 3 2]
